version: '3.3'
services:
  mysql:
    image: mysql:5.7.44
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql